"""create memberships table

Revision ID: 0882199d69c6
Revises: f1764007ad68
Create Date: 2021-08-05 16:15:04.978800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0882199d69c6"
down_revision = "f1764007ad68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("rit_email", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("given", sa.DateTime(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memberships")
    # ### end Alembic commands ###
