"""remove events table

Revision ID: 9c1fa448d2c3
Revises: 0882199d69c6
Create Date: 2021-08-18 13:43:14.286503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c1fa448d2c3"
down_revision = "0882199d69c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("committee", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("location", sa.TEXT(), nullable=True),
        sa.Column("start_date", sa.DATETIME(), nullable=False),
        sa.Column("end_date", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
