"""create golinks table

Revision ID: a0f1a6889cb2
Revises: 
Create Date: 2021-08-05 15:37:27.192347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0f1a6889cb2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "golinks",
        sa.Column("short_link", sa.String(length=64), nullable=False),
        sa.Column("full_link", sa.Text(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("short_link"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("golinks")
    # ### end Alembic commands ###
