"""create officers table

Revision ID: baf75d412163
Revises: a0f1a6889cb2
Create Date: 2021-08-05 16:04:29.064126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf75d412163'
down_revision = 'a0f1a6889cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee', sa.String(length=64), nullable=False),
    sa.Column('rit_email', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officers')
    # ### end Alembic commands ###
