"""add email to officer

Revision ID: eca0f2689c1b
Revises: d2a74a71709d
Create Date: 2021-08-26 17:01:53.257699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca0f2689c1b'
down_revision = 'd2a74a71709d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('email', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'email')
    # ### end Alembic commands ###
